// TVDB API V4
//
// Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes.
//
// The version of the OpenAPI document: 4.7.8
//
// Generated by: https://openapi-generator.tech

/// ArtworkExtendedRecord : extended artwork record

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArtworkExtendedRecord {
    #[serde(rename = "episodeId", skip_serializing_if = "Option::is_none")]
    pub episode_id: Option<i32>,
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i64>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(rename = "includesText", skip_serializing_if = "Option::is_none")]
    pub includes_text: Option<bool>,
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    #[serde(rename = "movieId", skip_serializing_if = "Option::is_none")]
    pub movie_id: Option<i32>,
    #[serde(rename = "networkId", skip_serializing_if = "Option::is_none")]
    pub network_id: Option<i32>,
    #[serde(rename = "peopleId", skip_serializing_if = "Option::is_none")]
    pub people_id: Option<i32>,
    #[serde(rename = "score", skip_serializing_if = "Option::is_none")]
    pub score: Option<f32>,
    #[serde(rename = "seasonId", skip_serializing_if = "Option::is_none")]
    pub season_id: Option<i32>,
    #[serde(rename = "seriesId", skip_serializing_if = "Option::is_none")]
    pub series_id: Option<i32>,
    #[serde(rename = "seriesPeopleId", skip_serializing_if = "Option::is_none")]
    pub series_people_id: Option<i32>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<crate::models::ArtworkStatus>>,
    #[serde(rename = "tagOptions", skip_serializing_if = "Option::is_none")]
    pub tag_options: Option<Vec<crate::models::TagOption>>,
    #[serde(rename = "thumbnail", skip_serializing_if = "Option::is_none")]
    pub thumbnail: Option<String>,
    #[serde(rename = "thumbnailHeight", skip_serializing_if = "Option::is_none")]
    pub thumbnail_height: Option<i64>,
    #[serde(rename = "thumbnailWidth", skip_serializing_if = "Option::is_none")]
    pub thumbnail_width: Option<i64>,
    /// The artwork type corresponds to the ids from the /artwork/types
    /// endpoint.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<i64>,
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<i64>,
}

impl Default for ArtworkExtendedRecord {
    fn default() -> Self {
        Self::new()
    }
}

impl ArtworkExtendedRecord {
    /// extended artwork record
    pub fn new() -> ArtworkExtendedRecord {
        ArtworkExtendedRecord {
            episode_id: None,
            height: None,
            id: None,
            image: None,
            includes_text: None,
            language: None,
            movie_id: None,
            network_id: None,
            people_id: None,
            score: None,
            season_id: None,
            series_id: None,
            series_people_id: None,
            status: None,
            tag_options: None,
            thumbnail: None,
            thumbnail_height: None,
            thumbnail_width: None,
            r#type: None,
            updated_at: None,
            width: None,
        }
    }
}
