// TVDB API V4
//
// Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes.
//
// The version of the OpenAPI document: 4.7.8
//
// Generated by: https://openapi-generator.tech

/// AwardCategoryBaseRecord : base award category record

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AwardCategoryBaseRecord {
    #[serde(rename = "allowCoNominees", skip_serializing_if = "Option::is_none")]
    pub allow_co_nominees: Option<bool>,
    #[serde(rename = "award", skip_serializing_if = "Option::is_none")]
    pub award: Option<Box<crate::models::AwardBaseRecord>>,
    #[serde(rename = "forMovies", skip_serializing_if = "Option::is_none")]
    pub for_movies: Option<bool>,
    #[serde(rename = "forSeries", skip_serializing_if = "Option::is_none")]
    pub for_series: Option<bool>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl Default for AwardCategoryBaseRecord {
    fn default() -> Self {
        Self::new()
    }
}

impl AwardCategoryBaseRecord {
    /// base award category record
    pub fn new() -> AwardCategoryBaseRecord {
        AwardCategoryBaseRecord {
            allow_co_nominees: None,
            award: None,
            for_movies: None,
            for_series: None,
            id: None,
            name: None,
        }
    }
}
