// TVDB API V4
//
// Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes.
//
// The version of the OpenAPI document: 4.7.8
//
// Generated by: https://openapi-generator.tech

/// AwardNomineeBaseRecord : base award nominee record

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AwardNomineeBaseRecord {
    #[serde(rename = "character", skip_serializing_if = "Option::is_none")]
    pub character: Option<Box<crate::models::Character>>,
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
    #[serde(rename = "episode", skip_serializing_if = "Option::is_none")]
    pub episode: Option<Box<crate::models::EpisodeBaseRecord>>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "isWinner", skip_serializing_if = "Option::is_none")]
    pub is_winner: Option<bool>,
    #[serde(rename = "movie", skip_serializing_if = "Option::is_none")]
    pub movie: Option<Box<crate::models::MovieBaseRecord>>,
    #[serde(rename = "series", skip_serializing_if = "Option::is_none")]
    pub series: Option<Box<crate::models::SeriesBaseRecord>>,
    #[serde(rename = "year", skip_serializing_if = "Option::is_none")]
    pub year: Option<String>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl Default for AwardNomineeBaseRecord {
    fn default() -> Self {
        Self::new()
    }
}

impl AwardNomineeBaseRecord {
    /// base award nominee record
    pub fn new() -> AwardNomineeBaseRecord {
        AwardNomineeBaseRecord {
            character: None,
            details: None,
            episode: None,
            id: None,
            is_winner: None,
            movie: None,
            series: None,
            year: None,
            category: None,
            name: None,
        }
    }
}
