// TVDB API V4
//
// Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes.
//
// The version of the OpenAPI document: 4.7.8
//
// Generated by: https://openapi-generator.tech

/// Character : character record

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Character {
    #[serde(rename = "aliases", skip_serializing_if = "Option::is_none")]
    pub aliases: Option<Vec<crate::models::Alias>>,
    #[serde(rename = "episode", skip_serializing_if = "Option::is_none")]
    pub episode: Option<Box<crate::models::RecordInfo>>,
    #[serde(rename = "episodeId", skip_serializing_if = "Option::is_none")]
    pub episode_id: Option<i32>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(rename = "isFeatured", skip_serializing_if = "Option::is_none")]
    pub is_featured: Option<bool>,
    #[serde(rename = "movieId", skip_serializing_if = "Option::is_none")]
    pub movie_id: Option<i32>,
    #[serde(rename = "movie", skip_serializing_if = "Option::is_none")]
    pub movie: Option<Box<crate::models::RecordInfo>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "nameTranslations", skip_serializing_if = "Option::is_none")]
    pub name_translations: Option<Vec<String>>,
    #[serde(
        rename = "overviewTranslations",
        skip_serializing_if = "Option::is_none"
    )]
    pub overview_translations: Option<Vec<String>>,
    #[serde(rename = "peopleId", skip_serializing_if = "Option::is_none")]
    pub people_id: Option<i32>,
    #[serde(rename = "personImgURL", skip_serializing_if = "Option::is_none")]
    pub person_img_url: Option<String>,
    #[serde(rename = "peopleType", skip_serializing_if = "Option::is_none")]
    pub people_type: Option<String>,
    #[serde(rename = "seriesId", skip_serializing_if = "Option::is_none")]
    pub series_id: Option<i32>,
    #[serde(rename = "series", skip_serializing_if = "Option::is_none")]
    pub series: Option<Box<crate::models::RecordInfo>>,
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<i64>,
    #[serde(rename = "tagOptions", skip_serializing_if = "Option::is_none")]
    pub tag_options: Option<Vec<crate::models::TagOption>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<i64>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "personName", skip_serializing_if = "Option::is_none")]
    pub person_name: Option<String>,
}

impl Default for Character {
    fn default() -> Self {
        Self::new()
    }
}

impl Character {
    /// character record
    pub fn new() -> Character {
        Character {
            aliases: None,
            episode: None,
            episode_id: None,
            id: None,
            image: None,
            is_featured: None,
            movie_id: None,
            movie: None,
            name: None,
            name_translations: None,
            overview_translations: None,
            people_id: None,
            person_img_url: None,
            people_type: None,
            series_id: None,
            series: None,
            sort: None,
            tag_options: None,
            r#type: None,
            url: None,
            person_name: None,
        }
    }
}
