// TVDB API V4
//
// Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes.
//
// The version of the OpenAPI document: 4.7.8
//
// Generated by: https://openapi-generator.tech

/// Company : A company record

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Company {
    #[serde(rename = "activeDate", skip_serializing_if = "Option::is_none")]
    pub active_date: Option<String>,
    #[serde(rename = "aliases", skip_serializing_if = "Option::is_none")]
    pub aliases: Option<Vec<crate::models::Alias>>,
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "inactiveDate", skip_serializing_if = "Option::is_none")]
    pub inactive_date: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "nameTranslations", skip_serializing_if = "Option::is_none")]
    pub name_translations: Option<Vec<String>>,
    #[serde(
        rename = "overviewTranslations",
        skip_serializing_if = "Option::is_none"
    )]
    pub overview_translations: Option<Vec<String>>,
    #[serde(rename = "primaryCompanyType", skip_serializing_if = "Option::is_none")]
    pub primary_company_type: Option<i64>,
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "parentCompany", skip_serializing_if = "Option::is_none")]
    pub parent_company: Option<crate::models::ParentCompany>,
    #[serde(rename = "tagOptions", skip_serializing_if = "Option::is_none")]
    pub tag_options: Option<Vec<crate::models::TagOption>>,
}

impl Default for Company {
    fn default() -> Self {
        Self::new()
    }
}

impl Company {
    /// A company record
    pub fn new() -> Company {
        Company {
            active_date: None,
            aliases: None,
            country: None,
            id: None,
            inactive_date: None,
            name: None,
            name_translations: None,
            overview_translations: None,
            primary_company_type: None,
            slug: None,
            parent_company: None,
            tag_options: None,
        }
    }
}
