// TVDB API V4
//
// Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes.
//
// The version of the OpenAPI document: 4.7.8
//
// Generated by: https://openapi-generator.tech

/// PeopleExtendedRecord : extended people record

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PeopleExtendedRecord {
    #[serde(rename = "aliases", skip_serializing_if = "Option::is_none")]
    pub aliases: Option<Vec<crate::models::Alias>>,
    #[serde(rename = "awards", skip_serializing_if = "Option::is_none")]
    pub awards: Option<Vec<crate::models::AwardBaseRecord>>,
    #[serde(rename = "biographies", skip_serializing_if = "Option::is_none")]
    pub biographies: Option<Vec<crate::models::Biography>>,
    #[serde(rename = "birth", skip_serializing_if = "Option::is_none")]
    pub birth: Option<String>,
    #[serde(rename = "birthPlace", skip_serializing_if = "Option::is_none")]
    pub birth_place: Option<String>,
    #[serde(rename = "characters", skip_serializing_if = "Option::is_none")]
    pub characters: Option<Vec<crate::models::Character>>,
    #[serde(rename = "death", skip_serializing_if = "Option::is_none")]
    pub death: Option<String>,
    #[serde(rename = "gender", skip_serializing_if = "Option::is_none")]
    pub gender: Option<i32>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(rename = "lastUpdated", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "nameTranslations", skip_serializing_if = "Option::is_none")]
    pub name_translations: Option<Vec<String>>,
    #[serde(
        rename = "overviewTranslations",
        skip_serializing_if = "Option::is_none"
    )]
    pub overview_translations: Option<Vec<String>>,
    #[serde(rename = "races", skip_serializing_if = "Option::is_none")]
    pub races: Option<Vec<serde_json::Value>>,
    #[serde(rename = "remoteIds", skip_serializing_if = "Option::is_none")]
    pub remote_ids: Option<Vec<crate::models::RemoteId>>,
    #[serde(rename = "score", skip_serializing_if = "Option::is_none")]
    pub score: Option<i64>,
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "tagOptions", skip_serializing_if = "Option::is_none")]
    pub tag_options: Option<Vec<crate::models::TagOption>>,
    #[serde(rename = "translations", skip_serializing_if = "Option::is_none")]
    pub translations: Option<Box<crate::models::TranslationExtended>>,
}

impl Default for PeopleExtendedRecord {
    fn default() -> Self {
        Self::new()
    }
}

impl PeopleExtendedRecord {
    /// extended people record
    pub fn new() -> PeopleExtendedRecord {
        PeopleExtendedRecord {
            aliases: None,
            awards: None,
            biographies: None,
            birth: None,
            birth_place: None,
            characters: None,
            death: None,
            gender: None,
            id: None,
            image: None,
            last_updated: None,
            name: None,
            name_translations: None,
            overview_translations: None,
            races: None,
            remote_ids: None,
            score: None,
            slug: None,
            tag_options: None,
            translations: None,
        }
    }
}
