// TVDB API V4
//
// Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes.
//
// The version of the OpenAPI document: 4.7.8
//
// Generated by: https://openapi-generator.tech

/// SeriesAirsDays : A series airs day record

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SeriesAirsDays {
    #[serde(rename = "friday", skip_serializing_if = "Option::is_none")]
    pub friday: Option<bool>,
    #[serde(rename = "monday", skip_serializing_if = "Option::is_none")]
    pub monday: Option<bool>,
    #[serde(rename = "saturday", skip_serializing_if = "Option::is_none")]
    pub saturday: Option<bool>,
    #[serde(rename = "sunday", skip_serializing_if = "Option::is_none")]
    pub sunday: Option<bool>,
    #[serde(rename = "thursday", skip_serializing_if = "Option::is_none")]
    pub thursday: Option<bool>,
    #[serde(rename = "tuesday", skip_serializing_if = "Option::is_none")]
    pub tuesday: Option<bool>,
    #[serde(rename = "wednesday", skip_serializing_if = "Option::is_none")]
    pub wednesday: Option<bool>,
}

impl Default for SeriesAirsDays {
    fn default() -> Self {
        Self::new()
    }
}

impl SeriesAirsDays {
    /// A series airs day record
    pub fn new() -> SeriesAirsDays {
        SeriesAirsDays {
            friday: None,
            monday: None,
            saturday: None,
            sunday: None,
            thursday: None,
            tuesday: None,
            wednesday: None,
        }
    }
}
